version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: "budgetTracker_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbPassword
      MYSQL_DATABASE: budget_db
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: budgetTracker_backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/budget_db
      SPRING_DATASOURCE_USERNAME: dbUser
      SPRING_DATASOURCE_PASSWORD: dbPassword

  frontend:
    build: ./frontend
    container_name: budgetTracker_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  mysql_data: